### ISSUE TITLE
Enable all the links and modify the webpage to accept Exodia Entries

### ISSUE THREAD

**Issue by shreyasbapat** [STAC-IITMandi/STAC-IITMandi.github.io#1]

**Comment by shreyasbapat** [comment]
Still needs a lot of enhancements

**Comment by shreyasbapat** [comment]
Even after merging #5  , it still needs a lot of changes to be done.

**Comment by chandan1794** [comment]
Links of problem statements are working after merging #5. The only thing which we need is forms for the 1st and the last event.

**Comment by shreyasbapat** [comment]
We will have the forms as soon as the website of Exodia is ready.

**Comment by shreyasbapat** [comment]
Closing this as Exodia things are done! And We already have #14
