### ISSUE TITLE
Improve Accessibility and SEO

### ISSUE THREAD

**Issue by ana-bautista** [STAC-IITMandi/STAC-IITMandi.github.io#108]
**Is your feature request related to a problem? Please describe.**
I believe that a website must always be responsive and accessible.
If you think like me, It's time to Improve it!

**Describe the solution you'd like**
In order to improve the accessibility some changes need to be done:
- [ ] Background and foreground colors do not have a sufficient contrast ratio.
- [ ] <html> element must have a valid value for the lang attribute
- [ ] Images must have alternate text
- [ ] `<ul>` and `<ol>` must only directly contain `<li>`, `<script>` or `<template>` elements
- [ ] Zooming and scaling must not be disabled
- [ ] Page must contain a level-one heading

**Additional context**
You may be interested in also improve SEO :)

**Comment by ana-bautista** [comment]
I can work on it, what do you say? ;)

**Comment by shreyasbapat** [comment]
Sure. Go ahead! I didn't actually had a look on what you proposed. I will follow up on PR.

**Comment by LalitNM** [comment]
This issue will be fixed in next version of webpage.
