### ISSUE TITLE
Ensure appropriate gap between two lines of title

### ISSUE THREAD

**Issue by abhijeetmanhas** [STAC-IITMandi/STAC-IITMandi.github.io#109]
**Describe the bug**
On opening title page (`index.html` file) and projects page `achievements.html` on tablet device like ipad, two different lines of title overap. 

**To Reproduce**
1. Go to 'files mentioned'
3. Look at 'heading div'.

**Expected behavior**
There should be proper gap between two lines, for other screen sizes too.

**Screenshots**
![Screenshot from 2019-10-22 23-38-54](https://user-images.githubusercontent.com/43112347/67316661-8165b700-f526-11e9-9972-15cd91f09822.png)
![Screenshot from 2019-10-22 23-38-34](https://user-images.githubusercontent.com/43112347/67316673-862a6b00-f526-11e9-8cff-69a26c03534f.png)

**Device (please complete the following information):**
Apple ipad 10.2 inch

**Comment by LalitNM** [comment]
@abhijeetmanhas I was checking [layout.css](https://github.com/STAC-IITMandi/STAC-IITMandi.github.io/blob/master/layout/styles/layout.css) I noticed that there media query is used at 10 places. Why can't we manage the code and make it easier to undersrtand for future developers. Moreover, we can easily solve this issue after specifying the width(no. of px) of tablets.

**Comment by LalitNM** [comment]
@abhijeetmanhas I have solved this issue, but yet the code-base is not good enough. #115 Check this pr.

**Comment by LalitNM** [comment]
Fixed. Check [web](stac.iitmandi.co.in).
