### ISSUE TITLE
Creating a page for details of Co-ordinators and Faculty Advisors

### ISSUE THREAD

**Issue by shreyasbapat** [STAC-IITMandi/STAC-IITMandi.github.io#12]
:beetle: **Problem** : The link to the Co-ordinator and Faculty Advisor takes us to page for vision.
:bulb:  **Solution** : Make 2 pages in the same format where the co-ordinator details and Faculty Advisor details will be shown.
:computer:  **Technologies** : You will learn basic HTML, CSS in doing this.

**Comment by Muzzammil15** [comment]
completed

**Comment by shreyasbapat** [comment]
Thanks! :tada:

**Comment by shreyasbapat** [comment]
#19  Referenced this
