### ISSUE TITLE
Add new pages to the site.

### ISSUE THREAD

**Issue by gajrajgchouhan** [STAC-IITMandi/STAC-IITMandi.github.io#142]
- [x] About ( Contact info of coordinators, core members description).
- [x] AstraX
- [x] Utkarsh
- [x] Zenith
- [x] Alumni's Info page.
- [x] Photogallery
- [x] Video gallery, embed videos from youtube channel of STAC

**Comment by LalitNM** [comment]
Fixed in #149.
