### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by LalitNM** [STAC-IITMandi/STAC-IITMandi.github.io#148]
Add the stac logo as favicon.

**Comment by tusharrao198** [comment]
Done in #149

**Comment by LalitNM** [comment]
@tusharrao198 see [favicon-wikipedia](https://en.m.wikipedia.org/wiki/Favicon).

**Comment by LalitNM** [comment]
Fixed in 125c3912987e76aba9dd5b660ce3c61d6649669d.
