### ISSUE TITLE
Add space to showcase events and their posters

### ISSUE THREAD

**Issue by shreyasbapat** [STAC-IITMandi/STAC-IITMandi.github.io#15]
:bulb: **Problem** : We don't have a page which showcases the posters and Prize money of the Events. 
:star:  **Bonus** : -None-

**Comment by abhijeetmanhas** [comment]
Would it be nice to keep all event posters in activities.html @ArshitaKalra @shreyasbapat ? Currently it is same as zenith

**Comment by ana-bautista** [comment]
I can do it, if you send me the images :)

**Comment by abhijeetmanhas** [comment]
@ana-bautista you can make 9-12 css cards with some random images as of now, with random text, in your Pull Request, later we will change it with actual posters. Description text will be shown on clicking on the card.

**Comment by LalitNM** [comment]
This issue will be fixed in next version of webpage.
