### ISSUE TITLE
Add information about STAC and its work

### ISSUE THREAD

**Issue by gajrajgchouhan** [STAC-IITMandi/STAC-IITMandi.github.io#156]
- [ ] On Home page add projects and achievements.
- [ ] Add information about STAC from wiki page and from current site.

**Comment by JanhaviShedge** [comment]
Which photos do we have for projects?

**Comment by LalitNM** [comment]
@gajrajgchouhan and @harnaman-hk, this issues doesn't have `urgent` or `ToDo` label. Is there something we need to fix before @JanhaviShedge can start working on this?

**Comment by LalitNM** [comment]
This has been fixed.
