### ISSUE TITLE
Change the complete appearance of the website

### ISSUE THREAD

**Issue by shreyasbapat** [STAC-IITMandi/STAC-IITMandi.github.io#16]
:question:  Is it feasible? Or more appropriately, is it worth doing? Garvit has suggested that the website does not look good.

**Comment by chandan1794** [comment]
Yes, it is feasible and very much necessary. Since, this is the only interface to the outer world. It should look good.
"Jo dikta he, wo bikta he" ;)

**Comment by b17126** [comment]
Hello sir , How can i find code for this html website?
because i think that we should modify our code to improve our website's looking.

**Comment by shreyasbapat** [comment]
@b17126  Can I know your name?

**Comment by shreyasbapat** [comment]
@akshat157  I made some changes in branches

**Comment by shreyasbapat** [comment]
Awesome work @akshat157 ! Great to see your efforts in completing this! Congratulations!

As there's no need to continue this thread, closing this now!
