### ISSUE TITLE
Customize navbar

### ISSUE THREAD

**Issue by harnaman-hk** [STAC-IITMandi/STAC-IITMandi.github.io#165]
Navigation bar needs to light-themed over dark backgrounds (header of home page) and dark-themed over light backgrounds. It should effectively transition between these two styles.

**Comment by LalitNM** [comment]
@harnaman-hk, what if we move whole website to dark theme? That would be great.

**Comment by tusharrao198** [comment]
> @harnaman-hk, what if we move whole website to dark theme? That would be great.

We can create a switch to dar mode button later. but right now  navbar visibility fixed when scrolled down.
Done in #167
