### ISSUE TITLE
Update navbar-menu to  open from left side  in mobile-view

### ISSUE THREAD

**Issue by tusharrao198** [STAC-IITMandi/STAC-IITMandi.github.io#169]
At present, the navbar-menu in mobile-view comes  out vertically downward. You need to update the menu to  slide out/in from left side to make it user-friendly in mobile-view.

**Comment by LalitNM** [comment]
@tusharrao198, I think the present UI is also good, do we still need to do this?

**Comment by tusharrao198** [comment]
Yes, It's looking good now. No need of this.
closing this issue.
