### ISSUE TITLE
Add former coordinators in the core team section.

### ISSUE THREAD

**Issue by tusharrao198** [STAC-IITMandi/STAC-IITMandi.github.io#174]
At present , the core teams section  contains  none of the former coordinators. You need to add them in the coordinators models  db . You can just do this simply going to django-admin page .

**Comment by masonwoodford** [comment]
Hello, I'm very new to open source projects but I would like to contribute, where would I be able to find a list of former coordinators?

**Comment by LalitNM** [comment]
Hi, @masonwoodford, I'm glad to see your participation in open source. We are always here to help you to get started with open source. But, this issue needs to be fixed by one of the members of @STAC-IITMandi. For you, I added `help wanted` label to #169 and #172. You can start working on them.

**Comment by tusharrao198** [comment]
Done in #179
