### ISSUE TITLE
checks failing in views.py

### ISSUE THREAD

**Issue by LalitNM** [STAC-IITMandi/STAC-IITMandi.github.io#189]
In every pull request some checks are failing in [views.py](https://github.com/STAC-IITMandi/STAC-IITMandi.github.io/blob/e39ed291a6914c3ae7b481704d1e01a4ba5b7fee/src/stac_iitmandi/views.py#L1-L135), They should be fixed.

**Comment by tusharrao198** [comment]
Issue solved in commit ff9d2d
