### ISSUE TITLE
Add team head section

### ISSUE THREAD

**Issue by LalitNM** [STAC-IITMandi/STAC-IITMandi.github.io#195]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see only two people leading the team, we actually have a few team heads as well.

**Describe the solution you'd like**
A section of team heads after coordinators apart from whole core team can be added.

**Describe alternatives you've considered**
I don't this that there is an alternative. We should add a `team heads` section.

**Additional context**
N/A

**Comment by tusharrao198** [comment]
@LalitNM , first i need a list of all the team heads and their team members

**Comment by tusharrao198** [comment]
resolved in pull request #199
