### ISSUE TITLE
Add deployment instructions

### ISSUE THREAD

**Issue by abhijeetmanhas** [STAC-IITMandi/STAC-IITMandi.github.io#196]
Extend Readme or create an instruction file how to run on localhost.

**Comment by harnaman-hk** [comment]
This is in context to local development deployment or final production deployment?

**Comment by abhijeetmanhas** [comment]
@harnaman-hk it is local deployment. You can add production as well if you wish but not necessary.

**Comment by harnaman-hk** [comment]
@abhijeetmanhas Local deployment instructions are already there in [CONTRIBUTING.md](https://github.com/STAC-IITMandi/STAC-IITMandi.github.io/blob/main/CONTRIBUTING.md)

**Comment by abhijeetmanhas** [comment]
Thanks. I'm closing the issue then.

**Comment by LalitNM** [comment]
@harnaman-hk, maybe we should add a link to contributing.md file in readme.md, to avoid such issues in future.
