### ISSUE TITLE
Add educational resource-material for people to engage with us.

### ISSUE THREAD

**Issue by priyanshsaxena** [STAC-IITMandi/STAC-IITMandi.github.io#28]
Presentations on the topics discussed in STAC meetings or links people find interesting. This can also include discussion-ideas that people post to us, as a blog or QA-portal.

**Comment by chandan1794** [comment]
This can also include all the videos of talks we had or will have.

**Comment by LalitNM** [comment]
This issue will be fixed in next version of webpage.
