### ISSUE TITLE
Banner Text not visible on small screens 

### ISSUE THREAD

**Issue by shreyasbapat** [STAC-IITMandi/STAC-IITMandi.github.io#38]
**Describe the bug**
:beetle: The text on the banner becomes out of visual area on small screens. 
**To Reproduce**
1. Go to 'stac-iitmandi.github.io'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] - Lenovo Z2 Plus
 - OS: [e.g. iOS8.1] - Oreo 8.1
 - Browser [e.g. stock browser, safari] - Chrome
 - Version [e.g. 22] ~

**Additional context**
**Possible Solutions**
:key: Replace the text with something else on the mobile view.

**Comment by akshat157** [comment]
Issue needs correction. The URL given isn't correct.
https://stac-iitmandi.github.io works!
