### ISSUE TITLE
Add proper wiki pages for future developers!

### ISSUE THREAD

**Issue by shreyasbapat** [STAC-IITMandi/STAC-IITMandi.github.io#42]
**Is your feature request related to a problem? Please describe.**
https://github.com/STAC-IITMandi/STAC-IITMandi.github.io/wiki
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chandan1794** [comment]
What all you want to add to the wiki page?
Let's make a list:

1. Purpose
2. Contributing guidelines
add items to the list in comments...

**Comment by shreyasbapat** [comment]
Contributing Guidelines are already there. Contributing.rst!
The point is, there must be some core principles, we must maintain a decorum and uniformity, some set of rules, 
Project Structure and how it should be in future.
How to release a version
When to release a version

**Comment by shreyasbapat** [comment]
https://github.com/STAC-IITMandi/STAC-IITMandi.github.io/wiki
Work is under serious progress :D 
@akshat157 @akashdakoor We need a Code of Conduct.

**Comment by LalitNM** [comment]
This issue will be fixed in next version of webpage.
