### ISSUE TITLE
Create a Text-Slideshow on the home page!

### ISSUE THREAD

**Issue by shreyasbapat** [STAC-IITMandi/STAC-IITMandi.github.io#50]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aayusss** [comment]
What is the material for the text slideshow?

**Comment by shreyasbapat** [comment]
Just put some random materail as of now. (You can use one which is currently there are slide it multiple times!)

**Comment by LalitNM** [comment]
This issue will be fixed in next version of webpage.
