### ISSUE TITLE
Add a 404 Page Not Found page.

### ISSUE THREAD

**Issue by akshat157** [STAC-IITMandi/STAC-IITMandi.github.io#52]
Add an 

> Error 404 Page not found

 error page, based on the template page already inside the repository.
Add this error page to all the currently not working hyperlinks.

**Comment by priyanshsaxena** [comment]
Have a look at this: https://www.figma.com/404/

An shtml page for 404 and 500 should be there. For this particular use-case of not having working URLs, we can probably add an engaging "Coming Up Soon" page, maybe with a site-map or a fun-fact related to astronomy.

**Comment by Ayaz1997** [comment]
I am working on this issue @akshat157

**Comment by shreyasbapat** [comment]
Closed in #61
