### ISSUE TITLE
Fix the mobile view of Activities Page

### ISSUE THREAD

**Issue by shreyasbapat** [STAC-IITMandi/STAC-IITMandi.github.io#55]
**Describe the bug**
Well... Just see the Zenith icon on mobile view, you'll know!
@akashdakoor 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by akashdakoor** [comment]
Oh xD will fix that after class

**Comment by MADPT** [comment]
I'll work on this issue

**Comment by MADPT** [comment]
You can check the fix in the #60 PR

**Comment by shreyasbapat** [comment]
Closed in #60 
Thanks @MADPT
