### ISSUE TITLE
Fixing the Links on the website

### ISSUE THREAD

**Issue by shreyasbapat** [STAC-IITMandi/STAC-IITMandi.github.io#6]
:bulb: 
Most of the links such as Vision, Inventory, Telescopes etc are not showing the data that is expected. 

:1st_place_medal: 
Separate every page on that section and make proper links

**Comment by AnweshDas** [comment]
do you want a frameset type wepage with all datas in a single page?

**Comment by shreyasbapat** [comment]
Anything that looks cool! You choice!

**Comment by Muzzammil15** [comment]
Completed , i will commit later

i pushed to master, can't commit again, have to make a branch

**Comment by shreyasbapat** [comment]
Still a small change that can be done is: Put the headings in the coloured area!

**Comment by akshat157** [comment]
Since the template has been changed now. this issue seems to be obsolete.
@shreyasbapat

**Comment by shreyasbapat** [comment]
True!
