### ISSUE TITLE
Rename activities.html to zenith.html ? And add Activities.html separately?

### ISSUE THREAD

**Issue by shreyasbapat** [STAC-IITMandi/STAC-IITMandi.github.io#62]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shreyasbapat** [comment]
Aah! I will do it myself! :confused: I am still not sure what to do!

**Comment by chandan1794** [comment]
What will activities.html contain then?
