### ISSUE TITLE
Some links and buttons are not responsive

### ISSUE THREAD

**Issue by chandan1794** [STAC-IITMandi/STAC-IITMandi.github.io#67]
**Describe the bug**
Some links and buttons are not responsive. Like **Inventory** in the nav-bar, **Archives**, **Alumni** and **Administer** in the footer. This is not user-friendly. Either we should remove them and show them when they are functioning properly or we should give a message indicating that we are still working on it.

**To Reproduce**
1. Go to any page of the website
2. Click on the above-mentioned links

**Expected behavior**
Should redirect to the intended pages.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by akshat157** [comment]
We can link them to a Error 404 page, with an "under construction" message. If the error page is already complete, the task is to link it to these buttons. If not, one can make the error page and link them.
Opening this up for hacktoberfest!

**Comment by chandan1794** [comment]
> We can link them to a Error 404 page, with an "under construction" message. If the error page is already complete, the task is to link it to these buttons. If not, one can make the error page and link them.
> Opening this up for hacktoberfest!

I'd suggest showing a tooltip message instead of designing a whole page, which will only contribute to frustration and also there should not be too many 404 ;)

**Comment by akshat157** [comment]
That sounds good as well! Leaving this upto whoever takes up the issue. :slightly_smiling_face:

**Comment by abisummers** [comment]
i'll take this if it hasn't already been done :)

**Comment by shreyasbapat** [comment]
Hi @abisummers ! There is no need to create one for inventory and administer! Coz, they are separate webapps ready to be deployed somewhere. 
For others, please create a PR with Screenshots of what you have done.

**Comment by jeel2308** [comment]
![bug](https://user-images.githubusercontent.com/42006763/47588967-731da300-d985-11e8-9f39-9669cf5ccc27.png)
i found this bug.which can be solved using flex or grid.

**Comment by shreyasbapat** [comment]
Hi, would you like to solve that?

**Comment by matheusagcosta** [comment]
Guys, I've created this popup option for those broken links. (PR above 🔝 )

What do you think?

![Screen Shot 2019-10-01 at 19 22 34](https://user-images.githubusercontent.com/3741582/66005223-30abf280-e481-11e9-996e-363081bad6bb.png)

**Comment by LalitNM** [comment]
@shreyasbapat I tried to solve this issue. Have a look at my PR #120.

**Comment by LalitNM** [comment]
This issue will be fixed in next version of webpage.
