### ISSUE TITLE
Creating an Inventory Management System

### ISSUE THREAD

**Issue by shreyasbapat** [STAC-IITMandi/STAC-IITMandi.github.io#7]
:beetle:  
**Problem** : Anyone takes anything from the STAC room and the co-ordinators and members are most of the time unaware of it. Another point is that the damage that happen to the equipment is untraceable.

:paintbrush: 
**Possible Solution** : Make a inventory management tool that can track who has taken what and can show all the records when needed.

**Comment by shreyasbapat** [comment]
@chandan1794  How about this?

**Comment by chandan1794** [comment]
Its a very good idea. But there are some questions lingering in the open daylight here.
1. Do we have a server to host a database? (It will need a database)
2. Should we implement the whole inventory management system? Since we can use an already implemented code and if we github a little, we will find one, suitable to our needs for sure.
3. Is this urgent? Since the website is still not responsive and content is still not proper.

**Comment by shreyasbapat** [comment]
Okay! 
1) Yes we do have a server to host a database. We can manage that.
2) No. We will just follow what every other open source organization does. We will take some already implemented code which probably has a MIT Licence.
3) Not urgent, but the things can be divided. Anyways, the goal is to learn things. Personally, as a club coordinator, I don't really care about the website. But yes, it is necessary.

**Comment by rtanmay** [comment]
Some doubts:-

1)If a person takes something from the STAC room, then will the person have to input the equipments taken or it is done by the co-ordinators?

2)To track the damage done, the equipments have to be checked by the co-ordinators after they are returned by the person right?

**Comment by shreyasbapat** [comment]
The person on his own will input the equipments. Yeah maybe! Core Members can keep an eye on equipments.  :stuck_out_tongue_winking_eye:

**Comment by Varunvaruns9** [comment]
I'll do it.
@shreyasbapat

**Comment by shreyasbapat** [comment]
Yeah! Start working on it!

**Comment by priyanshsaxena** [comment]
Assign @Varunvaruns9 to the issue @shreyasbapat

**Comment by shreyasbapat** [comment]
Have a look at this everyone: https://github.com/STAC-IITMandi/Inventory 
[Currently under development] Once it's upto the mark as per @Varunvaruns9 , I will make it open to contributions. And the PR's can be monitored by @swapsha96  @Varunvaruns9  and me!

**Comment by shreyasbapat** [comment]
Hi! @Varunvaruns9 ,
Can you help @akashdakoor and @ananya2501 deploy the Inventory on SnTC server?

(After making certain minimum changes)

**Comment by shreyasbapat** [comment]
Meanwhile, I will close this issue here!
Thanks! @Varunvaruns9 for the contribution!
