### ISSUE TITLE
Add a space for Zenith on index.html and feature some statistics!

### ISSUE THREAD

**Issue by shreyasbapat** [STAC-IITMandi/STAC-IITMandi.github.io#72]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MADPT** [comment]
I've added a section for the statistics (#74). You just need to fill it and change the colors to your taste.

**Comment by shreyasbapat** [comment]
Closed in #74
