### ISSUE TITLE
Aligning the footer in the center.

### ISSUE THREAD

**Issue by plxity** [STAC-IITMandi/STAC-IITMandi.github.io#78]
**Is your feature request related to a problem? Please describe.**
To make the UI/UX better we can align the footer in the center.

**Describe the solution you'd like**
Original footer
![2018-11-09 5](https://user-images.githubusercontent.com/28510494/48279897-fbb53c80-e477-11e8-9e9b-dd434299bb19.png)

After aligning it in center.
![2018-11-09 3](https://user-images.githubusercontent.com/28510494/48279792-a6792b00-e477-11e8-9700-7cc4e1bcc2ef.png)

**Comment by akshat157** [comment]
I had tried it while designing the site, felt the former is better than center aligned. I still request @akashdakoor @shreyasbapat to give their reviews though. :)

**Comment by akshat157** [comment]
I had tried it while designing the site, felt the former is better than center aligned. Would still request @akashdakoor @shreyasbapat to give their reviews though. :)

**Comment by shreyasbapat** [comment]
I feel center aligned also looks good!
We can merge it! GTG!

**Comment by plxity** [comment]
@akshat157 @shreyasbapat @sonaralee  Please review the Pull Request
