### ISSUE TITLE
Blank Read More links on homepage.

### ISSUE THREAD

**Issue by akshat157** [STAC-IITMandi/STAC-IITMandi.github.io#80]
Blank/hash links there on STAC homepage under the heading "Competitions held at STAC."

1. Go to https://stac-iitmandi.org
2. Scroll down to Competitions held at STAC.
3. Click on 'Read More' on the cards.

**Expected behavior**
Only show read more if its applicable?

**Comment by Tushar-Tyagi** [comment]
Can i work on this issue?

**Comment by Tushar-Tyagi** [comment]
![screenshot from 2019-01-23 16-40-20](https://user-images.githubusercontent.com/36927830/51602763-d5a72080-1f2d-11e9-9c48-748bd25142f7.png)
![screenshot from 2019-01-23 16-40-28](https://user-images.githubusercontent.com/36927830/51603121-e4420780-1f2e-11e9-8ed0-98e735d1fb23.png)
@shreyasbapat

**Comment by shreyasbapat** [comment]
Closed in #84
