### ISSUE TITLE
Footer center-aligned only on Homepage

### ISSUE THREAD

**Issue by akshat157** [STAC-IITMandi/STAC-IITMandi.github.io#81]
#78 aligned the footer for the website in center and the changes were merged.
Seems like the change was done only on index.html and not the other webpages including templage.html which is generally used while creating a new page.

Changes required:
Align the footer contents in center as can be seen on https://stac-iitmandi.org

**Comment by shreyasbapat** [comment]
Closed in #82  by @DumbMachine
