### ISSUE TITLE
Update all the links to stac.iitmandi.co.in

### ISSUE THREAD

**Issue by aashish-ak** [STAC-IITMandi/STAC-IITMandi.github.io#88]
**Describe the bug**
Update all the links from `stac-iitmandi.org` to `stac.iitmandi.co.in` 
Use `http://` instead of `https://`

**Comment by aashish-ak** [comment]
Also update the astrax link as relative link.

**Comment by LalitNM** [comment]
Fixed. You can check the [webpage](stac.iitmandi.co.in).
