### ISSUE TITLE
Compress the images on the website

### ISSUE THREAD

**Issue by akshat157** [STAC-IITMandi/STAC-IITMandi.github.io#94]
Currently used images are not all compressed. This leads to a larger website and slower loading speed on a viewer's browser.

The images can be compressed using any online utility.

**Comment by kartik1000** [comment]
Also, quality needs to be kept in my mind. Reducing  after certain quality might make the image look bad

**Comment by akshat157** [comment]
@kartik1000 Yes!

**Comment by tmoran18** [comment]
Hi, I will have a go at compressing the images if that's ok.

**Comment by LalitNM** [comment]
This issue will be fixed in next version of webpage.
