### ISSUE TITLE
Modify the error 404 page to match the website template

### ISSUE THREAD

**Issue by akshat157** [STAC-IITMandi/STAC-IITMandi.github.io#95]
Current Error 404 page is very different than the website visual scheme. Plus it has an unnecessary search bar. What can be done is:

- An error 404 page built on the given website template. `template.html` OR
- Create a new page but it should match the visual scheme of the website.

Also, if planning to include the search bar in the new one, it can be made functional or totally removed.

**Comment by ana-bautista** [comment]
If you don't mind, I'd like to contribute for the first time, fixing this issue.

**Comment by akshat157** [comment]
Sure, go ahead!

**Comment by ana-bautista** [comment]
> Sure, go ahead!

Open a PR yet :+1:

**Comment by LalitNM** [comment]
This issue will be fixed in next version of webpage.
