### ISSUE TITLE
Showcase EinsteinPy and MiraPy somewhere in the website :) 

### ISSUE THREAD

**Issue by shreyasbapat** [STAC-IITMandi/STAC-IITMandi.github.io#96]
Links: 
MiraPy: https://github.com/mirapy-org/MiraPy

EinsteinPy: 1)  https://einsteinpy.org
                   2) https://docs.einsteinpy.org
                   3) https://github.com/einsteinpy/einsteinpy

**Comment by abhijeetmanhas** [comment]
this is done I guess.
