### ISSUE TITLE
Add preloader for website

### ISSUE THREAD

**Issue by abhijeetmanhas** [STAC-IITMandi/STAC-IITMandi.github.io#98]
**Is your feature request related to a problem? Please describe.**
Website loading doesn't look nice on slow internet. Some images and text flash at unwanted location for a small moment which looks annoying.

**Describe the solution you'd like**
It would be better having a preloader, so that content is displayed only after it is fully loaded.It should satisfy some conditions:-

- It should be related to astronomy :)

- It must not consume too much space which may cause slow loading

- It can be related to color scheme or theme of website

**Additional context**
SCSS and JS can be used. You can look at various examples on codepen or some medium posts. Just google it!

**Comment by yash-bansod** [comment]
I'll look into this

**Comment by shreyasbapat** [comment]
But @akshat157 ? Is it good to have it? Or it will make the whole pipeline slow?

**Comment by akshat157** [comment]
Please don't add a preloader. Its unnecessary as of now I believe. @abhijeetmanhas @yash-bansod I'd do a :-1: to this one.

**Comment by abhijeetmanhas** [comment]
It is better to close it then. Thanks !
